FROM node:18.17.1-bullseye-slim

WORKDIR /app

COPY ./package.json .

RUN npm install --legacy-peer-deps

COPY . .

RUN npm run build  --verbose

ENV PATH="$PATH:./node_modules/.bin"

EXPOSE 5201

CMD ["npm", "run", "prod:next", "--host"]