name: Build and Push Docker Images

on:
  workflow_call:
    inputs:
      registry:
        required: true
        description: "The Docker registry URL"
        type: string
      context:
        required: true
        description: "The build context path for the Docker image"
        type: string
      image_name:
        required: true
        description: "The name of the Docker image"
        type: string
      ref:
        required: true
        description: "Branch name of the Preview"
        type: string
      tag:
        required: true
        description: "Tag name of the Preview Image"
        type: string

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 1
          persist-credentials: false

      - name: Get tags
        run: git fetch --tags origin

      - name: Get version
        if: ${{ inputs.image_name }} == 'workflows-service'
        id: version
        run: |
          TAG=$(git tag -l "$(echo ${{ inputs.image_name }}@)*" | sort -V -r | head -n 1)
          echo "tag=$TAG"
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "TAG=$TAG" >> "$GITHUB_ENV"
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "sha_short=$SHORT_SHA" >> "$GITHUB_OUTPUT"
          echo "SHORT_SHA=$SHORT_SHA" >> "$GITHUB_ENV"
      
      - name: Bump version
        id: bump-version
        if: ${{ inputs.image_name }} == 'workflows-service'
        uses: ./.github/actions/bump-version
        with:
          tag: ${{ steps.version.outputs.tag }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: 'arm64,arm'

      - name: Cache Docker layers
        id: cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
            ${{ runner.os }}-docker-

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker images
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.registry }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ inputs.tag }}
            type=sha,format=short
      
      - name: Print docker version outputs
        run: |
          echo "Metadata: ${{ steps.docker_meta.outputs.tags }}"
          if [[ "${{ inputs.image_name }}" == "workflows-service" ]]; then
            echo "sha_short: ${{ steps.version.outputs.sha_short }}"
            echo "bump-version-version: ${{ steps.bump-version.outputs.version }}"
            echo "bump-version-tag: ${{ steps.bump-version.outputs.tag }}"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            ${{ inputs.image_name == 'workflows-service' && format('"RELEASE={0}"\n"SHORT_SHA={1}"', steps.version.outputs.tag, steps.version.outputs.sha_short) || '' }}

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        continue-on-error: true
        with:
          image-ref: ${{ steps.docker_meta.outputs.tags }}
          format: 'table'
          ignore-unfixed: true
          exit-code: 1
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          timeout: '5m'
